### ISSUE TITLE
How to use the config in a new emacs?

### ISSUE THREAD

**Issue by justrajdeep** [gopar/.emacs.d#1]
Hi

I am brand new to emacs. I was using doom emacs for a while. I want to try your config. But not sure how to set it up. Can you please help me with the instructions?

TIA

**Comment by gopar** [comment]
Hey, sorry for late response. My config isn't really set up to be picked up and used as a kit like doom or the others alike. 

The main reason I have it picking is in case ppl would like to grab certain snippets and make them their own. 

I have settings that are specific to my own liking which others may not like :)

Closing this :)
